### ISSUE TITLE
Add Logo and Demo files

### ISSUE THREAD

**Issue by lvarayut** [lvarayut/relay-fullstack#1]
## Logo

![relay-fullstack-logo](https://cloud.githubusercontent.com/assets/4281887/14516854/792107ac-0231-11e6-95dd-86bb2b5197e3.png)
## Demo

![demo](https://cloud.githubusercontent.com/assets/4281887/13377800/9c4705a2-de1d-11e5-82cb-745e16d5b1c4.gif)
## Yeoman

![yeoman](https://cloud.githubusercontent.com/assets/4281887/15426353/3cad6240-1eb8-11e6-8400-deafceac8dc3.png)

**Comment by kulakowka** [comment]
It's awesome! Thank you @lvarayut !

**Comment by lvarayut** [comment]
@kulakowka Glad that you :heart:  it. I have planned to integrate it with many great tools, such as, Eslint, a testing framework, Flow, Yeoman, and etc. So, Stay tuned!

**Comment by kulakowka** [comment]
Yes, I am watching for changes to your repository.

P.S.
Most of all I would like to see an example of integration with databases.

**Comment by lvarayut** [comment]
That's one of the features noted in my long list, could be MongoDB. It will be integrated after Yeoman because I don't want to force everybody to use a chosen database. After having a Yeoman generator, they could choose whether they want to include the database or not.

**Comment by sachgits** [comment]
loves @kulakowka idea of integration with database best of all MongoDB.

**Comment by lvarayut** [comment]
@sachgits It has been noted.

**Comment by lvarayut** [comment]
I'm closing this issue as all the features mentioned here have been listed in #12. Please feel free to discuss your ideas in that issue.
