### ISSUE TITLE
ERROR in   TypeError: Cannot read property 'request' of undefined

### ISSUE THREAD

**Issue by webmobiles** [lvarayut/relay-fullstack#100]
when i execute npm install i got errors
## Actual Behavior

ERROR in   TypeError: Cannot read property 'request' of undefined
  
  - ExternalModuleFactoryPlugin.js:37 handleExternals
    [pelerelay]/[html-webpack-plugin]/[webpack]/lib/ExternalModuleFactoryPlugin.js:37:33
  
  - ExternalModuleFactoryPlugin.js:46 next
    [pelerelay]/[html-webpack-plugin]/[webpack]/lib/ExternalModuleFactoryPlugin.js:46:8
  
  - ExternalModuleFactoryPlugin.js:59 handleExternals
    [pelerelay]/[html-webpack-plugin]/[webpack]/lib/ExternalModuleFactoryPlugin.js:59:7
  
  - ExternalModuleFactoryPlugin.js:79 ExternalModuleFactoryPlugin.<anonymous>
    [pelerelay]/[html-webpack-plugin]/[webpack]/lib/ExternalModuleFactoryPlugin.js:79:5
  
  - NormalModuleFactory.js:246 applyPluginsAsyncWaterfall
    [pelerelay]/[webpack]/lib/NormalModuleFactory.js:246:4
  
  - Tapable.js:196 NormalModuleFactory.applyPluginsAsyncWaterfall
    [pelerelay]/[webpack]/[tapable]/lib/Tapable.js:196:70
  
  - NormalModuleFactory.js:230 NormalModuleFactory.create
    [pelerelay]/[webpack]/lib/NormalModuleFactory.js:230:8
  
  - Compilation.js:383 Compilation._addModuleChain
    [pelerelay]/[webpack]/lib/Compilation.js:383:17
  
  - Compilation.js:465 Compilation.addEntry
    [pelerelay]/[webpack]/lib/Compilation.js:465:8
  
  - SingleEntryPlugin.js:22 SingleEntryPlugin.<anonymous>
    [pelerelay]/[html-webpack-plugin]/[webpack]/lib/SingleEntryPlugin.js:22:15
  
  - Tapable.js:229 Compiler.applyPluginsParallel
    [pelerelay]/[webpack]/[tapable]/lib/Tapable.js:229:14
  
  - Compiler.js:505 
    [pelerelay]/[webpack]/lib/Compiler.js:505:8
  
  - Tapable.js:131 Compiler.applyPluginsAsyncSeries
    [pelerelay]/[webpack]/[tapable]/lib/Tapable.js:131:46
  
  - Compiler.js:498 Compiler.compile
    [pelerelay]/[webpack]/lib/Compiler.js:498:7
  
  - Compiler.js:284 Compiler.runAsChild
    [pelerelay]/[webpack]/lib/Compiler.js:284:7
  
  - compiler.js:70 
    [pelerelay]/[html-webpack-plugin]/lib/compiler.js:70:19

**Comment by lvarayut** [comment]
I can't reproduce the error on MacOS, I cloned the fresh project and successfully run `npm install`. Could you explain the steps to reproduce the error? This https://github.com/jantimon/html-webpack-plugin/issues/705 would be a great resource as well.

**Comment by protobuff3r** [comment]
I have the same error on Linux Mint with yarn and yarn start.
npm install and npm start working successfully.
Delete the yarn.lock, than yarn also works.

**Comment by manh-vv** [comment]
It seem that `yarn` is not good here.
```
-- works
rm -rf node_modules
npm install
npm start
```
I have the same error when
```
yarn && yarn start
```

**Comment by Neitsch** [comment]
Probably need to update `html-webpack-plugin` and `yarn`. Try this and let me know whether it works please :) https://github.com/facebookincubator/create-react-app/issues/2352

**Comment by webmobiles** [comment]
this repo , it works very well: https://github.com/jferrettiboke/react-auth-app-example

**Comment by lvarayut** [comment]
The issue should be solved in https://github.com/lvarayut/relay-fullstack/commit/904d83e8036961ca16dc7e83cc21e4fa1aa4056a. Please feel free to let us know if you still experienced the problem.
