### ISSUE TITLE
Material Design Light futures?

### ISSUE THREAD

**Issue by hubert-associates** [lvarayut/relay-fullstack#101]
Now that google is no longer supporting Material Design Light, roadmap update? Thanks!

**Comment by lvarayut** [comment]
Thanks for reporting. This's actually in our [Roadmap](https://github.com/lvarayut/relay-fullstack/issues/12#issuecomment-255637105), PR will be very welcome.

**Comment by hubert-associates** [comment]
Thanks, PR to what though? -- there is nothing comprable to MDL that I know. Also, relay modern is probably an easier step first.

**Comment by lvarayut** [comment]
As mentioned in the Roadmap,  MDL should be replaced with the vanilla CSS.
