### ISSUE TITLE
How to use subscription

### ISSUE THREAD

**Issue by neosarchizo** [lvarayut/relay-fullstack#102]
I also asked thie question in [stackoverflow](https://stackoverflow.com/questions/46255654/how-to-use-subscription-of-graphql-in-graphql-js). But anyone doesn't answer the question.  

I saw [the post](http://graphql.org/blog/subscriptions-in-graphql-and-relay/) about subscription of GraphQL. I want to use subscription of GraphQL in relay-fullstack.

How can I use subscription of GraphQL in relay-fullstack?

**Comment by Neitsch** [comment]
The issue of subscriptions is nothing specific to this project. You might want to create an issue in graphql, that it is lacking documentation.
The code to support it is here: https://github.com/graphql/graphql-js/tree/master/src/subscription
I think this tutorial will be helpful https://medium.com/react-native-training/building-chatty-part-6-graphql-subscriptions-b54df7d63e27
Once you have set up the server side you will also have to implement Relay subscriptions on the client side.

I'd be happy to review a PR when you have figured out how to do it.

**Comment by neosarchizo** [comment]
@Neitsch  Thanks!! It was a lot of help!
If I figure out, I'll share how to do it!
