### ISSUE TITLE
.gitignore not generated using advanced method

### ISSUE THREAD

**Issue by va1729** [lvarayut/relay-fullstack#108]
Thanks for the awesome starter kit!

The .gitignore file is not generated when I used the Yeoman. I manually copied the .gitignore and pasted it into my codebase. Please close the issue if there is a valid reason for not generating it.

## Expected Behavior
It should generate .gitignore

## Actual Behavior
It did not generate .gitignore file

## Steps to Reproduce
Follow the installation instructions under Advance usage in README
```
$ npm install -g yo generator-relay-fullstack
$ mkdir relay-fullstack && cd $_
$ yo relay-fullstack
$ npm start
```

**Comment by lvarayut** [comment]
Thanks @Vivekananda-Athukuri for reporting. We decided to drop the yeoman support, the yeoman branch won't contain the latest code version, please read more about it here https://github.com/lvarayut/relay-fullstack/issues/72#issuecomment-310847653. Please follow this [instruction](https://github.com/lvarayut/relay-fullstack#basic) to get the latest version.

**Comment by lvarayut** [comment]
I'm going to close this issue for now. Please feel free to continue the discussion here if you had more question.
