### ISSUE TITLE
SSL in dev and prod?

### ISSUE THREAD

**Issue by reactor81** [lvarayut/relay-fullstack#109]
I don't see a way to do ssl in dev and prod. Is this possible with the webpack and HL running? Has anyone seen a tutorial / PR for this?

**Comment by ncrmro** [comment]
@reactor81 I believe this is outside of the scope of this project and webpack. 

Essentially you could try a reverse proxy like apache, nginx, or traefik.

**Comment by reactor81** [comment]
Ah, yes, I could see how it might be out of scope, @ncrmro , thanks. Will close.
