### ISSUE TITLE
Server Side Rendering support

### ISSUE THREAD

**Issue by alexhawkins** [lvarayut/relay-fullstack#11]
Do you have plans to add SSR to your kit? SSR is essential for SEO. Current solutions seem to be a bit hacky but here is an an example of it being done:  https://github.com/codefoundries/isomorphic-material-relay-starter-kit

**Comment by lvarayut** [comment]
Thanks @alexhawkins for the link. I'll take a look at it. Any PR would be also really welcomed.

**Comment by lvarayut** [comment]
I'm closing this issue as the feature has been listed in #12. Please feel free to discuss further in that issue.
