### ISSUE TITLE
user authentification

### ISSUE THREAD

**Issue by keon** [lvarayut/relay-fullstack#13]
How should we implement user authentification in GraphQL?
Most practices I saw are RESTful (for user auth) + GraphQL (for general use)

**Comment by lvarayut** [comment]
You could inject your own DefaultNetworkLayer as following:

``` js
Relay.injectNetworkLayer(
  new Relay.DefaultNetworkLayer('http://localhost:3000/graphql', {
    headers: {
      Authorization: 'Bearer ' + token
    }
  })
);
```

Take a look at [this awesome article](https://auth0.com/blog/2015/10/06/getting-started-with-relay/).
