### ISSUE TITLE
NPM Issue 

### ISSUE THREAD

**Issue by anchika** [lvarayut/relay-fullstack#16]
Hi,

I am new to relay and react . I followed the steps and got the npm issue on npm install.:

npm ERR! peerinvalid The package eslint-plugin-react@5.0.1 does not satisfy its
siblings' peerDependencies requirements!
npm ERR! peerinvalid  Peer eslint-config-airbnb@7.0.0 wants eslint-plugin-react@^
4.3.0

I changed the dependency in package.json for eslint-plugin-react to 4.3.0. The npm install was successful then but on doing npm start I got following error:

$ npm start

> relay-fullstack@1.0.0 start c:\Users\ancagarwal\Usage Analytics\relay\insights
> 
> nodemon --watch 'server/data/*_/_.js' --exec 'npm run update && babel-node ser
> ver/index.js'

[nodemon] 1.9.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: 'server/data/*_/_.js'
[nodemon] starting `'npm run update`
''npm' is not recognized as an internal or external command,
operable program or batch file.
[nodemon] app crashed - waiting for file changes before starting...

Please let me know if I am doing anything wrong.

**Comment by lvarayut** [comment]
@anchika It seems like the `npm` hasn't been set to your PATH. Are you using window? You might take a look at this [StackOverflow question](http://stackoverflow.com/questions/20992723/npm-is-not-recognized-as-internal-or-external-command-operable-program-or-bat).

**Comment by anchika** [comment]
I am using windows. Npm was set in path but it seems like some issues with windows. When I tried same steps in Ubuntu, everything worked fine.

**Comment by lvarayut** [comment]
That's interesting. Did you try to add `;C:\Program Files\nodejs\` to the end of your Path variable and restart your command prompt?

**Comment by blackpost38** [comment]
@anchika why don't you check this out https://github.com/remy/nodemon/issues/389. Maybe, this issue looks like a problem that you have

**Comment by lvarayut** [comment]
I'm going to close this issue since it seems to be not related to Relay Fullstack. Please feel free to continue the discussion here if you had more question.

**Comment by agungsb** [comment]
I manage to solve the problem by change the following script:

`nodemon --watch 'server/data/**/*.js' --exec 'npm run update && babel-node server/index.js'`

with

`"nodemon --watch server/data/**/*.js --exec \"npm run update && babel-node server/index.js\""`

It is located inside `package.json`. I hope this will help somoeone out there who face the same problem as I had.
