### ISSUE TITLE
NPM Issue

### ISSUE THREAD

**Issue by flt123** [lvarayut/relay-fullstack#2]
Hi,

Great stack. Had issues with npm start. Find attached the npm issue log and let me know if I'm doing something wrong at my end. Running on Mac.

**Comment by lvarayut** [comment]
I'm running fine with NodeJs v5.8.0, same as yours, on Mac. Can you try to move it out of the Dropbox directory and try again?

**Comment by flt123** [comment]
Thanks for your quick response. Tried that and still getting same error. I suspect some lodash dependency somewhere. Updated log attached.

**Comment by lvarayut** [comment]
Have you ever run `npm install` before? If yes, what's happen if you run `npm install lodash && npm start`?

**Comment by flt123** [comment]
That did the trick, looks like some dependencies are using older version of lodash. Thanks a lot

**Comment by lvarayut** [comment]
No problem :smile:
