### ISSUE TITLE
any chance of including some mutations or auth examples?

### ISSUE THREAD

**Issue by andyfen** [lvarayut/relay-fullstack#26]
maybe as a separate branch or something but it would really be helpful, resources for both these are thin on the web.

thanks.

**Comment by lvarayut** [comment]
Thanks for asking. I included the Mutation example in our [Roadmap](https://github.com/lvarayut/relay-fullstack/issues/12).

**Comment by lvarayut** [comment]
Just quick notify, the example of mutation has been implemented in this ff982bfac7d159b3643ce60507a5464c81b563c5 :)
