### ISSUE TITLE
Consider use of "favicons-webpack-plugin"

### ISSUE THREAD

**Issue by RyLeeHarrison** [lvarayut/relay-fullstack#27]
In the interest of improvement and further movement of the project, I recommend the use of the simple  [favicons webpack plugin dependency](https://www.npmjs.com/package/favicons-webpack-plugin), because it will reduce the size of the application, clean up the HTML template, offer more user customizable features for their particular use case.

**Comment by lvarayut** [comment]
Thanks for your suggestion. I have tried the plugin few months ago. At that time, it was very early stage and had some potential problem, I don't remember exactly what it was.  However, the plugin  might be improved and definitely worth to try. I'll check it out asap. Any PR will also be very welcomed.

**Comment by RyLeeHarrison** [comment]
Excellent!

**Comment by lvarayut** [comment]
Implemented in 497de427b1b69e9bf3405ab8c2c1ccb9cc03e5e2 :)
