### ISSUE TITLE
npm Install error!

### ISSUE THREAD

**Issue by ardavank** [lvarayut/relay-fullstack#29]
I cloned the repo and ran "npm install" and I got the following error message:

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package eslint-plugin-jsx-a11y@2.0.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer eslint-config-airbnb@9.0.1 wants eslint-plugin-jsx-a11y@^1.2.0

**Comment by ardavank** [comment]
I even tried it with node v6.1.0

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.1.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.1.0
npm ERR! npm  v2.15.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package eslint-plugin-jsx-a11y@2.0.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer eslint-config-airbnb@9.0.1 wants eslint-plugin-jsx-a11y@^1.2.0

**Comment by ardavank** [comment]
I fixed the issue by upgrading the npm to version 3.8.6

**Comment by lvarayut** [comment]
Thanks for sharing the solution.
