### ISSUE TITLE
Relay is returning strange alias for connections via REQUIRED_CHILDREN after mutation

### ISSUE THREAD

**Issue by Rohit-cheddr** [lvarayut/relay-fullstack#34]
For some reason when I do a mutation and get a return value with `REQUIRED_CHILDREN` in `getConfigs`, connections are being returned with a strange alias: `_tierItems2EmfF3`where it should be `tierItems`.

When I make the same mutation through GraphiQL, the connection is returned properly.

I am not sure if this is some kind of configuration issue, but I have no idea what could be causing this.

**Comment by lvarayut** [comment]
Thanks for your question. I think it's a mechanism inside Relay. You should be able to access  `tierItems` as normal inside your application.
