### ISSUE TITLE
Loading custom css for external libraries

### ISSUE THREAD

**Issue by rohit-ravikoti** [lvarayut/relay-fullstack#35]
Hi!
This starter kit has been tremendously helpful in helping me get started. Just wanted to say thanks!

I was wondering how I would be able to include custom css files to override those provided by an external library (like auth0-lock). It looks like how stylesheets are currently loaded are through local scoping. Is there anything in place for global scoping?

Thanks!

**Comment by lvarayut** [comment]
Hi @rohit-ravikoti! I'm very glad that this project's helpful to you. We're using css-modules to handle our css files, which are local scope by default. You can use `:global` keyword to switch to global scope, please take a look at the example on the [Exceptions](https://github.com/css-modules/css-modules#exceptions) for more details.

**Comment by rohit-ravikoti** [comment]
got it! Thanks!
