### ISSUE TITLE
Integrate Postgres with yeoman

### ISSUE THREAD

**Issue by lvarayut** [lvarayut/relay-fullstack#40]
Integrate Postgres in **canary** branch which will be used in our yeoman generator.

**Comment by ugiacoman** [comment]
Not sure about yeoman, but I am currently working on integrating with Postgres. I'll post back any success haha

**Comment by lvarayut** [comment]
Thanks, @ugiacoman, that would be useful 👍

**Comment by ugiacoman** [comment]
@lvarayut I ended up using [Postgraphql](https://github.com/calebmer/postgraphql) for the integration. So far it's working pretty well but not sure if that is the type of integration you'd like to go for. Essentially what it does is allow you to create an SQL schema and it takes care of the GraphQL usage.

**Comment by lvarayut** [comment]
`Postgraphql` looks good to me. If you could integrate it with our yeoman, in the **canary** branch, that would be really helpful to a lot of people.

**Comment by ugiacoman** [comment]
Sounds good, I'll toy around with it for a while, figure out the quirks, and send a PR. Unfortunately, can't give you an ETA.

**Comment by lvarayut** [comment]
That's fine. Thanks @ugiacoman. Look forward for it 😄
