### ISSUE TITLE
How to use multiple ViewerQueries

### ISSUE THREAD

**Issue by Danjavia** [lvarayut/relay-fullstack#44]
I try to implement a relayContainer for some of components, but without success, ever need and ViewerQuery for this task.

Can U help me?

e.g. a postList component, userList component... etc.

**Comment by lvarayut** [comment]
Hi @Danjavia, thanks for the question. Normally, you can reuse the provided [ViewerQuery.js](https://github.com/lvarayut/relay-fullstack/blob/master/client/routes/ViewerQuery.js) to create a new container.

**Comment by Danjavia** [comment]
Ok Many thanks. I will to review this Many thanks.
