### ISSUE TITLE
Error when run npm run deploy with browserHistory

### ISSUE THREAD

**Issue by Danjavia** [lvarayut/relay-fullstack#46]
When running 

```
npm run deploy
```

the build dist run correctly but running on surge.sh or simple http server using python. the browserHistory doesn't show the routes.

On the other hand when run npm start the browserHistory runs perfectly.

Some idea?

```
import { browserHistory, applyRouterMiddleware, Router } from 'react-router';

<Router history={browserHistory} routes={Route} render={applyRouterMiddleware(useRelay)} environment={Relay.Store} />
```

**Comment by lvarayut** [comment]
Thanks for the question. This seems to be not related to Relay Fullstack. You might need to consult the `react-router` team.  Please feel free to continue the discussion here if you had more question.
