### ISSUE TITLE
Production should not use babel-node

### ISSUE THREAD

**Issue by ugiacoman** [lvarayut/relay-fullstack#47]
Source: [Babel CLI Documentation](https://babeljs.io/docs/usage/cli/#babel-node)

> babel-node not meant for production use
> 
> You should not be using babel-node in production. It is unnecessarily heavy, with high memory usage due to the cache being stored in memory. You will also always experience a startup performance penalty as the entire app needs to be compiled on the fly.

Research that may help: https://medium.com/@Cuadraman/how-to-use-babel-for-production-5b95e7323c2f#.vg3mo8a5m

This is on my TODO list.

**Comment by lvarayut** [comment]
Thanks @ugiacoman for reporting this issue. Any PR will be very welcomed.

**Comment by arnif** [comment]
Here is my solution: #48
