### ISSUE TITLE
Using node-dev?

### ISSUE THREAD

**Issue by ghost** [lvarayut/relay-fullstack#49]
Wouldn't using node-dev be better than using node-demon? I recently switched to it and it seems good.

**Comment by lvarayut** [comment]
Thanks @pyros2097 for your suggestion. I've never used `node-dev` before. However, based on my first glance, there are some [critical issues](https://github.com/fgnass/node-dev/issues) such as 
- Don't set NODE_ENV
- node-dev exits after restarting
- Doesn't run on Win 7

I don't think we should switch to it, at least for now.

**Comment by lvarayut** [comment]
I'm going to close this issue for now. Please feel free to continue the discussion here if you had more question.
