### ISSUE TITLE
Deploying relay-fullstack on AWS

### ISSUE THREAD

**Issue by witbybit** [lvarayut/relay-fullstack#58]
Are there any instructions available on how to deploy this to AWS? I am new to AWS as well as Relay and my understanding is that I have to use AWS Elastic Beanstalk to deploy the backend and S3 for frontend.

**Comment by lvarayut** [comment]
Hi @nikhilag, thanks for your question. We don't have any instructions for deploying to a specific platform right now, however, deploying Relay Fullstack on AWS shouldn't be different from deploying on other servers. [This article](https://docs.aws.amazon.com/codedeploy/latest/userguide/github-integ-tutorial.html) would help you get started.

**Comment by lvarayut** [comment]
I'm going to close this issue for now. Please feel free to continue the discussion here if you had more question.
