### ISSUE TITLE
Show more function in the Feature list

### ISSUE THREAD

**Issue by ngocdiep** [lvarayut/relay-fullstack#59]
Hi there,
I'm the beginner in Relayjs. I just wanna add the show more function in the Feature list.
I tried to add the function like this:
 
```
    this.props.relay.setVariables({
      count: $count + 2
    });
```
but I got the error: TypeError: Cannot read property 'features' of null

Somebody can help me!!

Best regards

**Comment by lvarayut** [comment]
Hi @ngocdiep, thanks for the question. The error might occur [here](https://github.com/lvarayut/relay-fullstack/blob/master/client/components/Feature/FeatureComponent.js#L18). I'm not sure why `this.props.viewer` is `null`.  You might want to start checking from there.

**Comment by ngocdiep** [comment]
Hi @lvarayut,
Thanks for your answer!
I haven't found the solution yet to fix that.
It's very great if you can add some functions like search, paging or load more to this project!

Best thanks,

**Comment by lvarayut** [comment]
Hi @ngocdiep, thanks for your suggestion. I will need to focus on the main functionalities listed on #12 first, but any PR would be really welcomed. I'm going to close this issue for now. Please feel free to continue the discussion here if you had more question.
