### ISSUE TITLE
Refresh in production mode causes error

### ISSUE THREAD

**Issue by jkettmann** [lvarayut/relay-fullstack#6]
Refreshing the browser on any page except home causes an error "cannot get /...". This must be a configuration problem between react-routers browser history and the server.

In short: when you navigate to e.g. /login via the menu react-router is taking care of navigation without server interaction. On refresh though a request with url /login is send to server which is not available.

See [this answer](http://stackoverflow.com/a/28076359) on stackoverflow

**Comment by lvarayut** [comment]
Thanks for reporting. I'll take a look at it soon. If you could make a PR, it'll be very welcomed.

**Comment by lvarayut** [comment]
Fixed by https://github.com/lvarayut/relay-fullstack/commit/e661e23d4f15d03bfad82bc669d097974844ec89.
