### ISSUE TITLE
Migrate Relay Mutation

### ISSUE THREAD

**Issue by Neitsch** [lvarayut/relay-fullstack#60]
Relay 2, which is supposed to be there soon changes the style of mutations. This part is already publically available and represented in the API (https://facebook.github.io/relay/docs/api-reference-relay-graphql-mutation.html). In addition these mutations are simpler to write. Thus the feature mutation should be changed to be a Relay.GraphQLMutation

**Comment by lvarayut** [comment]
Hi @Neitsch, thanks for your suggestion. This is absolutely important, PR would be really welcomed.

**Comment by Neitsch** [comment]
Was a little busy, will try to get on that now.

**Comment by lvarayut** [comment]
Thanks @Neitsch 👍  Look forward for it.
