### ISSUE TITLE
React hot loader not working?

### ISSUE THREAD

**Issue by rogersp** [lvarayut/relay-fullstack#67]
Running into an issue where hot reload of React components is not working as expected. There is a HMR warning in the console which may be related:

![image](https://cloud.githubusercontent.com/assets/2909421/23000067/a60d8cf0-f393-11e6-83b4-087ed6c63c71.png)

Here are the steps I've performed, on a Win10x64 machine:

- Clone repo
- `npm install`
- Change `package.json` scripts entry for `start`

from:
```
nodemon --watch server/data/**/*.js --exec \"npm run update && ./node_modules/.bin/babel-node server/index.js\"
``` 
to: 
```
nodemon --watch server/data/**/*.js --exec \"npm run update && babel-node server/index.js\"
```
 Notice the elimination of `./node_modules/.bin/`. This is a quick and dirty fix for Windows which doesn't like the local babel-node reference.

- `npm start`
- Open http://localhost:3000/login in browser.
- Open `client/components/Login/LoginComponent.js`, change  page heading text and save.
- Page heading text is not changed, and warning message appears in developer console.

My expectation is the login page heading would change without a full-page refresh.  Any idea why this is not working as expected?

**Comment by Neitsch** [comment]
I can confirm the error, but the fix does not work for me (please let us know which babel-cli/babel-node version you use). I'd speculate that react-hot-loader causes this, last updated in #62. However, before the PR, the error message was 

> The following modules couldn't be hot updated: (They would need a full reload!)

@ncrmro might be more familiar with HMR

**Comment by ncrmro** [comment]
@rogersp @Neitsch can confirm master and canary branches HMR isn't being triggered atm. Checking it out.

**Comment by ncrmro** [comment]
Actually that was cause I had two webpack dev servers except custom ports were sending one's request to the other. 

HMR is working with the latest canary branch. I've just checked.

 I'm working on  OS X. Haven't done much dev on windows.

**Comment by rogersp** [comment]
@Neitsch @ncrmro  can confirm HMR does work for react components in canary branch on Windows.

**Comment by ncrmro** [comment]
@rogersp great going to close for now!
