### ISSUE TITLE
Compiling server with a webpack instead of babel-node script

### ISSUE THREAD

**Issue by AdamZaczek** [lvarayut/relay-fullstack#77]
Wouldn't that be more real-life like? I can submit a pull in a weekend ;)

**Comment by lvarayut** [comment]
I still keep looking very much forward to your awesome PR 😄

**Comment by AdamZaczek** [comment]
Thanks for reminder, already did so ;)  Here lives the not so huge pull: https://github.com/lvarayut/relay-fullstack/pull/78
