### ISSUE TITLE
Question - Integrating Socket.io

### ISSUE THREAD

**Issue by BlakeBrown** [lvarayut/relay-fullstack#83]
Just curious how to go about integrating socket.io into this stack?

Socket.io docs say to use:
```
var app = require('express')();
var server = require('http').createServer(app);
var io = require('socket.io')(server);
io.on('connection', function(){ /* … */ });
server.listen(3000);
``` 

However, passing relayServer fails since it's a WebpackDevServer. Not sure how to resolve this while keeping HMR functional.

**Comment by lvarayut** [comment]
It's a long time that I don't touch Socket.io. I'm not quite sure if I could help here. Could you take a look on https://github.com/webpack/webpack-dev-server/issues/76 and https://stackoverflow.com/questions/33584724/how-to-use-socket-io-together-with-webpack-hot-middleware?

**Comment by Neitsch** [comment]
For dev you will have to proxy webpack dev server (https://github.com/webpack/webpack-dev-server/issues/283#issuecomment-162163329). For prod you will need to proxy via express (https://github.com/chimurai/http-proxy-middleware/blob/master/examples/websocket/index.js).

Please close unless you need any more help 😄

**Comment by BlakeBrown** [comment]
Thank you guys! I think that's enough to get me started :)

Feel free to close the issue!
