### ISSUE TITLE
Warnings about PropTypes  and React.createClass 

### ISSUE THREAD

**Issue by graforlock** [lvarayut/relay-fullstack#84]
Just cloned and did `npm install` and when it compiles, console shows: 

```
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
```

```
Warning: RouterContext: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.
```

It did not do it a couple of days ago, i am guessing its something new?

**Comment by Neitsch** [comment]
Yep, FB merged a huge PR recently. Will fix, PR is also welcome.

**Comment by ncrmro** [comment]
Newest version of react is moving prototypes and createclass to its own package

**Comment by Neitsch** [comment]
All our React classes are ES6, this warning is coming from react-router, please file an issue there.

**Comment by Neitsch** [comment]
https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

**Comment by Neitsch** [comment]
Thanks for reporting. I opened the PR, other than that we will have to wait for all dependencies to update. If this problem persists in two weeks, feel free to reopen, so that we find a workaround.
