### ISSUE TITLE
Have a plan to upgrade from Relay Classic to Relay Modern ?

### ISSUE THREAD

**Issue by haruthuc** [lvarayut/relay-fullstack#89]
Hi, I'm newbie with React & Relay , GraphQL. I very liked relay-fullstack repo. Have a plan to upgrade Relay Classic to Relay Modern ?

**Comment by arvinsim** [comment]
I think this would be great since Relay Modern was just recently released. A lot of people would want to try it out, especially those who want to compare it with Apollo.

**Comment by Neitsch** [comment]
I wish we could. We are waiting for a upstream dependency. Canary has it integrated ( #86 ), but unfortunately I don't feel comfortable integrating it into master until react-router-relay merges the changes ( relay-tools/react-router-relay#235 ).
Cheers

**Comment by mayhs19** [comment]
Hi All,
What is the current status of this upgrade ? Will there be a merge to master sometime soon ?

**Comment by Neitsch** [comment]
TBH, I don't think so, but you should be able to work off experimental (I actually prefer that branch, since it adds flow). We will need a week after the new release of relay router.

**Comment by mayhs19** [comment]
Thanks for the update !

**Comment by lvarayut** [comment]
@Neitsch, the issue on `react-router-relay` has been merged. Would you like to merge the canary to master now?

**Comment by Neitsch** [comment]
Oh yeah, I forgot about that. Will try to get around to that soon!

**Comment by nicois** [comment]
any updates? We are about to kick off a new project and really want to start with the cleaner relay modern, based on the rest of what you have done.

**Comment by Neitsch** [comment]
I apologize that this is taking so long. Work is keeping my very busy right now. I'd recommend to use the experimental branch, since it is on modern and gives you some extras too. Simply replace the reference to my repo with the router version for modern.

**Comment by JasonShin** [comment]
I can probably have a look at implementing few roadmap items to canary branch this weekend (browsersync and JWT). What do you think about having dockerfile example as well (+ docker compose for frontend and backend orchestration)?

**Comment by lvarayut** [comment]
I'm updating all the dependencies to the latest versions and will merge the `canary` to the `master` very soon.

**Comment by lvarayut** [comment]
Closed by https://github.com/lvarayut/relay-fullstack/issues/72#issuecomment-310847653
