### ISSUE TITLE
Queries not working in children components 

### ISSUE THREAD

**Issue by fameoflight** [lvarayut/relay-fullstack#90]
Any idea why you need to explicitly pass viewer to Footer rather than it picking it up from FooterContainer

https://github.com/lvarayut/relay-fullstack/blob/master/client/components/App/AppComponent.js#L28

**Comment by Neitsch** [comment]
Have you tried removing it? It might just be an error on my part. I'll have a look in the next days.

**Comment by fameoflight** [comment]
Yeah i did try removing it it didn't work.

**Comment by Neitsch** [comment]
Ah, actually the code is right. Relay does not inject props. It's mostly used for queries. See a similar Todo example.
https://github.com/relayjs/relay-examples/blob/master/TodoMVC/components/TodoList.js

**Comment by fameoflight** [comment]
@Neitsch is there any way to make queries work in children components I thought the whole point of relay was to keep queries near to component. This kind of break that paradigm.

**Comment by Neitsch** [comment]
The query still does it's job and is right by the component. It's all more about what attributes will be fetched / needed and whether to rerender.
