### ISSUE TITLE
Security issue with deploy script

### ISSUE THREAD

**Issue by jkettmann** [lvarayut/relay-fullstack#94]
All server side files are exposed when running the deploy script. You can see the file structure afterwards in the following image. The compiled app files are located next to the compiled server files. 

![screenshot 2017-06-30 15 34 31](https://user-images.githubusercontent.com/9722792/27738444-a336ce7e-5dab-11e7-8d34-98a2d0804c61.png)

This directory is made public via express.static. So if you use the deploy script to publish your app in production everyone can look up all server side code. As an example you can run npm run deploy and go to localhost:3000/index.js (see below image). This is the compiled server entry.

![screenshot 2017-06-30 15 37 37](https://user-images.githubusercontent.com/9722792/27738110-bf9a5046-5daa-11e7-8b72-578266b888f9.png)

This is not possible on the deployed heroku version, because there the server side code is compiled to directory **lib**, so it is not located inside the static directory.

**Comment by ncrmro** [comment]
@jkettmann Thanks for discovering this potential issue, we love pull requests! Also maybe you could post some potential solutions here we could discuss.
