### ISSUE TITLE
'.' is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by sanjeevmalagi1** [lvarayut/relay-fullstack#97]
I am having trouble starting relay-full stack project. Plz Help
[https://stackoverflow.com/questions/44970484/is-not-recognized-as-an-internal-or-external-command-for-relay-full-stack/44983742#44983742](https://stackoverflow.com/questions/44970484/is-not-recognized-as-an-internal-or-external-command-for-relay-full-stack/44983742#44983742)

**Comment by lvarayut** [comment]
Did you try with the latest version of Relay Fullstack? Because the problem should have been solved with https://github.com/lvarayut/relay-fullstack/pull/96

**Comment by lvarayut** [comment]
I'm going to close this issue since the issue has been solved with #96 . Please feel free to continue the discussion here if you had more question.
