### ISSUE TITLE
warning "webpack-dev-server@2.5.0" has incorrect peer dependency "webpack@^2.2.0".

### ISSUE THREAD

**Issue by webmobiles** [lvarayut/relay-fullstack#99]
## Actual Behavior
when i execute 'yarn install'

I get:
warning "webpack-dev-server@2.5.0" has incorrect peer dependency "webpack@^2.2.0".

i'm using node v8.1.2

**Comment by Neitsch** [comment]
Could you try pinning the version to 2.2.0 (by removing the ^ in the line for the webpack dependency).

I'll try to look into what's causing this issue.

**Comment by Neitsch** [comment]
Feel free to comment and reopen if this is still an issue.
